
default: test_nongui

test_nongui: lorentz_transform virtual_M

test_all: test_bijection test_gnuplot_out test_gl_draw

lorentz_transform:
	sh test.sh lorentz_transform

virtual_M:
	sh test.sh virtual_M

gnuplot_out:
	sh test.sh gnuplot_out

gl_draw:
	sh test.sh gl_draw
